drawer_tree_initiator:
  ros__parameters:
    plugins:
      - drawer_change_state_request_action_bt_node
      - open_drawer_action_bt_node
      - drawer_status_condition_bt_node
      - move_electric_drawer_action_bt_node
      - base_error_decorator_node
      - reset_decorator_bt_node
      - initialize_led_vector_action_bt_node
      - publish_led_action_bt_node
      - partial_colorize_leds_action_bt_node
      - get_blackboard_value_action_bt_node
      - publish_drawer_status_action_bt_node
      - import_environment_led_color_action_bt_node
      - publish_state_feedback_action_bt_node
    bt_path: "/workspace/install/drawer_sm/trees/trees/drawer_sequence.xml"
    trigger_topic: "trigger_drawer_tree"
    main_tree: "BehaviorTree"
    tree_tick_time: 10
