name: shared_widgets
description: Contains widgets which are used by the robot_frontend aswell as the web_frontend
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter

  shared_data_models:
    path: ../shared_data_models
  zoom_widget: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
