- ros_topic_name: "/front_laser/scan"
  gz_topic_name: "/front_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/bpearl_laser/scan/points"
  gz_topic_name: "/bpearl_laser/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_realsense_camera/color"
  gz_topic_name: "/front_realsense_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_realsense_camera/depth"
  gz_topic_name: "/front_realsense_camera/front_realsense_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_realsense_camera/depth/points"
  gz_topic_name: "/front_realsense_camera/front_realsense_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_oak_d_camera/color"
  gz_topic_name: "/back_top_oak_d_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_oak_d_camera/depth"
  gz_topic_name: "/back_top_oak_d_camera/back_top_oak_d_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_oak_d_camera/depth/points"
  gz_topic_name: "/back_top_oak_d_camera/back_top_oak_d_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "back_top_oak_d_camera/color_camera_info"
  gz_topic_name: "/back_top_oak_d_camera/back_top_oak_d_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_top_oak_d_camera/color"
  gz_topic_name: "/front_top_oak_d_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_top_oak_d_camera/depth"
  gz_topic_name: "/front_top_oak_d_camera/front_top_oak_d_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_top_oak_d_camera/depth/points"
  gz_topic_name: "/front_top_oak_d_camera/front_top_oak_d_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "front_top_oak_d_camera/color_camera_info"
  gz_topic_name: "/front_top_oak_d_camera/front_top_oak_d_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_realsense_camera/color"
  gz_topic_name: "/back_top_realsense_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_realsense_camera/depth"
  gz_topic_name: "/back_top_realsense_camera/back_top_realsense_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_realsense_camera/depth/points"
  gz_topic_name: "/back_top_realsense_camera/back_top_realsense_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "back_top_realsense_camera/color_camera_info"
  gz_topic_name: "/back_top_realsense_camera/back_top_realsense_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_realsense_camera/color"
  gz_topic_name: "/back_realsense_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_realsense_camera/depth"
  gz_topic_name: "/back_realsense_camera/back_realsense_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_realsense_camera/depth/points"
  gz_topic_name: "/back_realsense_camera/back_realsense_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/imu/data"
  gz_topic_name: "/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS
